using System.Threading.Tasks;
using TheSSS.DICOMViewer.Security.DTOs;

namespace TheSSS.DICOMViewer.Security.Interfaces;

/// <summary>
/// Defines the contract for logging security-related audit events.
/// This service is responsible for persisting audit records generated by the SecurityOrchestrator.
/// Implemented in Infrastructure (e.g., Infrastructure.AuditLogRepository).
/// Requirements Addressed: REQ-7-001, REQ-7-027.
/// </summary>
public interface IAuditLogService
{
    /// <summary>
    /// Logs a security event.
    /// </summary>
    /// <param name="eventDetails">The details of the security event to log.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task LogSecurityEventAsync(SecurityEventDetailsDto eventDetails);
}