using Microsoft.EntityFrameworkCore.Migrations;

namespace TheSSS.DICOMViewer.Infrastructure.Persistence.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Auto-generated by EF Core tools
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Auto-generated by EF Core tools
        }
    }
}